export enum AppErrorCodes {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
  MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER",
  MALFORMED_AUTH_HEADER = "MALFORMED_AUTH_HEADER",
}
